import { AchievementsProps } from "../types/achievements";

export const achievementsAPI: AchievementsProps[] = [
  { icon: "/achievements/Achievement_Charmed.png", name: "CHARMED", percent: "75.6" },
  { icon: "/achievements/Achievement_Falsehood.png", name: "FK_DEFEAT", percent: "69.8" },
  { icon: "/achievements/Achievement_Test_of_Resolve.png", name: "HORNET_1", percent: "60.9" },
  { icon: "/achievements/Achievement_Connection.png", name: "STAG_STATION_HALF", percent: "47.1" },
  { icon: "/achievements/Achievement_Protected.png", name: "PROTECTED", percent: "45.8" },
  { icon: "/achievements/Achievement_Illumination.png", name: "SOUL_MASTER_DEFEAT", percent: "44.8" },
  { icon: "/achievements/Achievement_Respect.png", name: "MANTIS_LORDS", percent: "44.3" },
  { icon: "/achievements/Achievement_Soulful.png", name: "SOULFUL", percent: "41.7" },
  { icon: "/achievements/Achievement_Honour.png", name: "DUNG_DEFENDER", percent: "40.6" },
  { icon: "/achievements/Achievement_Release.png", name: "BROKEN_VESSEL", percent: "39.7" },
  { icon: "/achievements/Achievement_Enchanted.png", name: "ENCHANTED", percent: "38.1" },
  { icon: "/achievements/Achievement_Beast.png", name: "BEAST", percent: "36.7" },
  { icon: "/achievements/Achievement_Grubfriend.png", name: "GRUBFRIEND", percent: "36.6" },
  { icon: "/achievements/Achievement_Proof_of_Resolve.png", name: "HORNET_2", percent: "36.6" },
  { icon: "/achievements/Achievement_Attunement.png", name: "ATTUNEMENT", percent: "36.2" },
  { icon: "/achievements/Achievement_Warrior.png", name: "COLOSSEUM_1", percent: "35.7" },
  { icon: "/achievements/Achievement_Teacher.png", name: "TEACHER", percent: "35.6" },
  { icon: "/achievements/Achievement_Watcher.png", name: "WATCHER", percent: "35.3" },
  { icon: "/achievements/Achievement_Cartographer.png", name: "MAP", percent: "34.5" },
  { icon: "/achievements/Achievement_Conqueror.png", name: "COLOSSEUM_2", percent: "32.7" }, 
  { icon: "/achievements/Achievement_Hope.png", name: "STAG_STATION_ALL", percent: "31.4" },
  { icon: "/achievements/Achievement_Execution.png", name: "TRAITOR_LORD", percent: "31.4" },
  { icon: "/achievements/Achievement_Obsession.png", name: "COLLECTOR", percent: "29.6" },
  { icon: "/achievements/Achievement_Peace.png", name: "DREAM_BROKEN_VESSEL", percent: "28.8" },
  { icon: "/achievements/Achievement_Awakening.png", name: "AWAKENING", percent: "28.4" },
  { icon: "/achievements/Achievement_Rivalry.png", name: "ZOTE", percent: "27.5" },
  { icon: "/achievements/Achievement_Strength.png", name: "DREAM_FK", percent: "25.0" },
  { icon: "/achievements/Achievement_Grand_Performance.png", name: "GRIMM", percent: "24.9" },
  { icon: "/achievements/Achievement_Metamorphosis.png", name: "METAMORPHOSIS", percent: "24.8" },
  { icon: "/achievements/Achievement_Void.png", name: "VOID", percent: "24.2" },
  { icon: "/achievements/Achievement_Worldsoul.png", name: "WORLDSOUL", percent: "24.0" },
  { icon: "/achievements/Achievement_Witness.png", name: "QUIRREL_EPILOGUE", percent: "23.4" },
  { icon: "/achievements/Achievement_Mortality.png", name: "DREAM_SOUL_MASTER_DEFEAT", percent: "22.6" },
  { icon: "/achievements/Achievement_The_Hollow_Knight.png", name: "ENDING_A", percent: "22.1" },
  { icon: "/achievements/Achievement_Dark_Romance.png", name: "GREY_PRINCE", percent: "20.5" },
  { icon: "/achievements/Achievement_Solace.png", name: "MOURNER", percent: "19.9" },
  { icon: "/achievements/Achievement_Blessed.png", name: "BLESSED", percent: "19.3" },
  { icon: "/achievements/Achievement_Ascension.png", name: "ASCENSION", percent: "19.1" },
  { icon: "/achievements/Achievement_Masked.png", name: "MASKED", percent: "19.0" },
  { icon: "/achievements/Achievement_Fool.png", name: "COLOSSEUM_3", percent: "18.7" },
  { icon: "/achievements/Achievement_Dream_No_More.png", name: "ENDING_C", percent: "18.2" },
  { icon: "/achievements/Achievement_Purity.png", name: "NAILSMITH_KILL", percent: "17.7" },
  { icon: "/achievements/Achievement_Completion.png", name: "COMPLETION", percent: "17.6" },
  { icon: "/achievements/Achievement_Memory.png", name: "WHITE_DEFENDER", percent: "17.4" },
  { icon: "/achievements/Achievement_Sealed_Siblings.png", name: "ENDING_B", percent: "17.4" },
  { icon: "/achievements/Achievement_Brotherhood.png", name: "PANTHEON1", percent: "15.9" },
  { icon: "/achievements/Achievement_Inspiration.png", name: "PANTHEON2", percent: "15.0" },
  { icon: "/achievements/Achievement_Ritual.png", name: "NIGHTMARE_GRIMM", percent: "14.9" },
  { icon: "/achievements/Achievement_Focus.png", name: "PANTHEON3", percent: "11.0" },
  { icon: "/achievements/Achievement_Happy_Couple.png", name: "NAILSMITH_SPARE", percent: "9.6" },
  { icon: "/achievements/Achievement_Soul_and_Shade.png", name: "PANTHEON4", percent: "8.7" },
  { icon: "/achievements/Achievement_Banishment.png", name: "BANISHMENT", percent: "7.6" },
  { icon: "/achievements/Achievement_Keen_Hunter.png", name: "HUNTER_1", percent: "7.2" },
  { icon: "/achievements/Achievement_Neglect.png", name: "NEGLECT", percent: "7.2" },
  { icon: "/achievements/Achievement_True_Hunter.png", name: "HUNTER_2", percent: "6.6" },
  { icon: "/achievements/Achievement_Passing_of_the_Age.png", name: "MR_MUSHROOM", percent: "6.4" },
  { icon: "/achievements/Achievement_Pure_Completion.png", name: "COMPLETIONGG", percent: "6.1" },
  { icon: "/achievements/Achievement_Speedrun_1.png", name: "SPEEDRUN_1", percent: "5.9" },
  { icon: "/achievements/Achievement_Speed_Completion.png", name: "SPEED_COMPLETION", percent: "5.0" },
  { icon: "/achievements/Achievement_Speedrun_2.png", name: "SPEEDRUN_2", percent: "4.9" },
  { icon: "/achievements/Achievement_Embrace_the_Void.png", name: "ENDINGD", percent: "4.7" },
  { icon: "/achievements/Achievement_Steel_Soul.png", name: "STEELSOUL", percent: "4.2" },
  { icon: "/achievements/Achievement_Steel_Heart.png", name: "STEELSOUL_COMPLETION", percent: "3.5" },
];

export enum AchievementName {
  CHARMED = "Charmed",
  FK_DEFEAT = "Falsehood",
  HORNET_1 = "Test of Resolve",
  STAG_STATION_HALF = "Connection",
  PROTECTED = "Protected",
  SOUL_MASTER_DEFEAT = "Illumination",
  MANTIS_LORDS = "Respect",
  SOULFUL = "Soulful",
  DUNG_DEFENDER = "Honour",
  BROKEN_VESSEL = "Release",
  ENCHANTED = "Enchanted",
  BEAST = "Beast",
  GRUBFRIEND = "Grubfriend",
  HORNET_2 = "Proof of Resolve",
  ATTUNEMENT = "Attunement",
  COLOSSEUM_1 = "Warrior",
  TEACHER = "Teacher",
  WATCHER = "Watcher",
  MAP = "Cartographer",
  COLOSSEUM_2 = "Conqueror",
  STAG_STATION_ALL = "Hope",
  TRAITOR_LORD = "Execution",
  COLLECTOR = "Obsession",
  DREAM_BROKEN_VESSEL = "Peace",
  AWAKENING = "Awakening",
  ZOTE = "Rivalry",
  DREAM_FK = "Strengh",
  GRIMM = "Grand Performance",
  METAMORPHOSIS = "Metamorphosis",
  VOID = "Void",
  WORLDSOUL = "Worldsoul",
  QUIRREL_EPILOGUE = "Witness",
  DREAM_SOUL_MASTER_DEFEAT = "Mortality",
  ENDING_A = "The Hollow Knight",
  GREY_PRINCE = "Dark Romance",
  MOURNER = "Solace",
  BLESSED = "Blessed",
  ASCENSION = "Ascension",
  MASKED = "Masked",
  COLOSSEUM_3 = "Fool",
  ENDING_C = "Dream No More",
  NAILSMITH_KILL = "Purity",
  COMPLETION = "Completion",
  WHITE_DEFENDER = "Memory",
  ENDING_B = "Sealed Siblings",
  PANTHEON1 = "Brotherhood",
  PANTHEON2 = "Inspiration",
  NIGHTMARE_GRIMM = "Ritual",
  PANTHEON3 = "Focus",
  NAILSMITH_SPARE = "Happy Couple",
  PANTHEON4 = "Soul & Shade",
  BANISHMENT = "Banishment",
  HUNTER_1 = "Keen Hunter",
  NEGLECT = "Neglect",
  HUNTER_2 = "True Hunter",
  MR_MUSHROOM = "Passing of the Age",
  COMPLETIONGG = "Pure Completion",
  SPEEDRUN_1 = "Speedrun 1",
  SPEED_COMPLETION = "Speed Completion",
  SPEEDRUN_2 = "Speedrun 2",
  ENDINGD = "Embrace the Void",
  STEELSOUL = "Steelsoul",
  STEELSOUL_COMPLETION = "Steel Heart",
}
export const mapApiAchievementsToEnum = (
  apiAchievements: { icon: string; name: string; percent: string }[]
): { icon: string; name: AchievementName; percent: string }[] => {
  return apiAchievements.map((apiAchievement) => {
    const enumKey = apiAchievement.name.toUpperCase().replace(/ /g, "_");
    if (AchievementName[enumKey as keyof typeof AchievementName]) {
      return {
        icon: apiAchievement.icon,
        name: AchievementName[enumKey as keyof typeof AchievementName],
        percent: apiAchievement.percent,
      };
    } else {
      console.warn(`Conquista não encontrada no enum: ${apiAchievement.name}`);
      return {
        icon: apiAchievement.icon,
        name: apiAchievement.name as AchievementName,
        percent: apiAchievement.percent,
      };
    }
  });
};

export const processedAchievements = mapApiAchievementsToEnum(achievementsAPI);
console.log(processedAchievements);
