import { AchievementsProps } from "../types/achievements";

export const achievementsAPI: AchievementsProps[] = [
  {
    icon: "/achievements/Achievement_Charmed.png",
    name: "CHARMED",
    percent: "75.6",
    description: "Acquire your first Charm",
    howToGet: "Find and learn all three Spells: Vengeful Spirit, Desolate Dive, and Shade Soul.",
    prerequisites: [],
    location: ["Forgotten Crossroads", "City of Tears", "Ancient Basin"],
  },
  {
    icon: "/achievements/Achievement_Falsehood.png",
    name: "FK_DEFEAT",
    percent: "69.8",
    description: "Defeat the False Knight.",
    howToGet: "Defeat the False Knight boss found at the end of the Forgotten Crossroads.",
    prerequisites: [],
    location: ["Forgotten Crossroads"],
  },
  {
    icon: "/achievements/Achievement_Test_of_Resolve.png",
    name: "HORNET_1",
    percent: "60.9",
    description: "Defeat Hornet in Greenpath.",
    howToGet: "Defeat the Hornet boss found at the end of Greenpath.",
    prerequisites: [],
    location: ["Greenpath"],
  },
  {
    icon: "/achievements/Achievement_Connection.png",
    name: "STAG_STATION_HALF",
    percent: "47.1",
    description: "Open half of the Stag Stations.",
    howToGet: "Find and ring the bell to open at least four of the eight Stag Stations.",
    prerequisites: [],
    location: [
      "Forgotten Crossroads",
      "Greenpath",
      "City of Tears",
      "Fungal Wastes",
      "Royal Waterways",
      "Deepnest",
      "Ancient Basin",
      "Kingdom's Edge",
    ],
  },
  {
    icon: "/achievements/Achievement_Protected.png",
    name: "PROTECTED",
    percent: "45.8",
    description: "Acquire 4 Mask Shards",
    howToGet: "Find and collect four Mask Shards. These will increase your health by one full Mask.",
    prerequisites: [],
    location: ["Forgotten Crossroads", "Greenpath", "City of Tears", "Fungal Wastes"],
  },
  {
    icon: "/achievements/Achievement_Illumination.png",
    name: "SOUL_MASTER_DEFEAT",
    percent: "44.8",
    description: "Defeat the Soul Master.",
    howToGet: "Defeat the Soul Master boss found in the Soul Sanctum in the City of Tears.",
    prerequisites: [],
    location: ["City of Tears"],
  },
  {
    icon: "/achievements/Achievement_Respect.png",
    name: "MANTIS_LORDS",
    percent: "44.3",
    description: "Defeat the Mantis Lords.",
    howToGet: "Defeat the three Mantis Lords bosses found in the Mantis Village in the Fungal Wastes.",
    prerequisites: [],
    location: ["Fungal Wastes"],
  },
  {
    icon: "/achievements/Achievement_Soulful.png",
    name: "SOULFUL",
    percent: "41.7",
    description: "Acquire 3 Vessel Fragments",
    howToGet: "Find and collect three Soul Vessels. Each adds one slot to your Soul meter.",
    prerequisites: [],
    location: ["Forgotten Crossroads", "City of Tears", "Ancient Basin"],
  },
  {
    icon: "/achievements/Achievement_Honour.png",
    name: "DUNG_DEFENDER",
    percent: "40.6",
    description: "Defeat the Dung Defender.",
    howToGet: "Defeat the Dung Defender boss found in the Royal Waterways.",
    prerequisites: [],
    location: ["Royal Waterways"],
  },
  {
    icon: "/achievements/Achievement_Release.png",
    name: "BROKEN_VESSEL",
    percent: "39.7",
    description: "Defeat the Broken Vessel.",
    howToGet: "Defeat the Broken Vessel boss found in the Ancient Basin.",
    prerequisites: ["Descent"],
    location: ["Ancient Basin"],
  },
  {
    icon: "/achievements/Achievement_Enchanted.png",
    name: "ENCHANTED",
    percent: "38.1",
    description: "Acquire half of Hallownest's Charms",
    howToGet: "Find and acquire 20 Charms scattered throughout Hallownest.",
    prerequisites: [],
    location: [
      "Forgotten Crossroads",
      "Greenpath",
      "City of Tears",
      "Fungal Wastes",
      "Royal Waterways",
      "Deepnest",
      "Ancient Basin",
      "Kingdom's Edge",
      "Crystal Peak",
      "Howling Cliffs",
      "Queen's Gardens",
      "Fog Canyon",
    ],
  },
  {
    icon: "/achievements/Achievement_Beast.png",
    name: "BEAST",
    percent: "36.7",
    description: "Destroy Herrah the Beast",
    howToGet: "Defeat the Dreamer boss Lurien the Watcher found in the Watcher's Spire in the City of Tears.",
    prerequisites: [],
    location: ["City of Tears"],
  },
  {
    icon: "/achievements/Achievement_Grubfriend.png",
    name: "GRUBFRIEND",
    percent: "36.6",
    description: "Rescue half of the Grubs.",
    howToGet: "Find and free at least 23 of the 46 Grubs trapped in jars throughout Hallownest.",
    prerequisites: [],
    location: [
      "Forgotten Crossroads",
      "Greenpath",
      "City of Tears",
      "Fungal Wastes",
      "Royal Waterways",
      "Deepnest",
      "Ancient Basin",
      "Kingdom's Edge",
      "Crystal Peak",
      "Howling Cliffs",
      "Queen's Gardens",
      "Fog Canyon",
    ],
  },
  {
    icon: "/achievements/Achievement_Proof_of_Resolve.png",
    name: "HORNET_2",
    percent: "36.6",
    description: "Defeat Hornet in Kingdom's Edge.",
    howToGet: "Defeat the Hornet boss found at the end of Kingdom's Edge.",
    prerequisites: ["King's Brand"],
    location: ["Kingdom's Edge"],
  },
  {
    icon: "/achievements/Achievement_Attunement.png",
    name: "ATTUNEMENT",
    percent: "36.2",
    description: "Collect 600 Essence",
    howToGet: "Collect 600 Essence of the dream nail",
    prerequisites: ["Mothwing Cloak"],
    location: ["Kingdom's Edge"],
  },
  {
    icon: "/achievements/Achievement_Warrior.png",
    name: "COLOSSEUM_1",
    percent: "35.7",
    description: "Complete the Trial of the Warrior",
    howToGet: "Survive and complete the first trial in the Colosseum of Fools.",
    prerequisites: ["Mantis Claw"],
    location: ["Kingdom's Edge"],
  },
  {
    icon: "/achievements/Achievement_Teacher.png",
    name: "TEACHER",
    percent: "35.6",
    description: "Destroy Monomon the Teacher",
    howToGet: "Defeat the Dreamer boss Herrah the Beast found in Deepnest.",
    prerequisites: [],
    location: ["Deepnest"],
  },
  {
    icon: "/achievements/Achievement_Watcher.png",
    name: "WATCHER",
    percent: "35.3",
    description: "Destroy Lurien the Watcher",
    howToGet: "Defeat the Watcher Lurien boss found at the top of the Watcher's Spire in the City of Tears.",
    prerequisites: [],
    location: ["City of Tears"],
  },
  {
    icon: "/achievements/Achievement_Cartographer.png",
    name: "MAP",
    percent: "34.5",
    description: "Acquire a map of each area",
    howToGet: "Unluck all maps of Hallownest",
    prerequisites: [],
    location: [
      "Forgotten Crossroads",
      "Greenpath",
      "City of Tears",
      "Fungal Wastes",
      "Royal Waterways",
      "Deepnest",
      "Ancient Basin",
      "Kingdom's Edge",
      "Crystal Peak",
      "Howling Cliffs",
      "Queen's Gardens",
      "Fog Canyon",
      "The Hive",
    ],
  },
  {
    icon: "/achievements/Achievement_Conqueror.png",
    name: "COLOSSEUM_2",
    percent: "32.7",
    description: "Complete the Trial of the Conqueror",
    howToGet: "Survive and complete the second trial in the Colosseum of Fools.",
    prerequisites: ["Desolate Dive"],
    location: ["Kingdom's Edge"],
  },
  {
    icon: "/achievements/Achievement_Hope.png",
    name: "STAG_STATION_ALL",
    percent: "31.4",
    description: "Open all of Hallownest's Stag Stations and discover the Stag Nest",
    howToGet: "Find and ring the bell to open all eight Stag Stations.",
    prerequisites: [],
    location: [
      "Forgotten Crossroads",
      "Greenpath",
      "City of Tears",
      "Fungal Wastes",
      "Royal Waterways",
      "Deepnest",
      "Ancient Basin",
      "Kingdom's Edge",
    ],
  },
  {
    icon: "/achievements/Achievement_Execution.png",
    name: "TRAITOR_LORD",
    percent: "31.4",
    description: "Defeat the Traitor Lord.",
    howToGet: "Defeat the Traitor Lord boss found at the end of the Queen's Gardens.",
    prerequisites: ["Descent"],
    location: ["Queen's Gardens"],
  },
  {
    icon: "/achievements/Achievement_Obsession.png",
    name: "COLLECTOR",
    percent: "29.6",
    description: "Defeat the Collector",
    howToGet: "Defeat the Collector boss found at the Tower of Love",
    prerequisites: [],
    location: [
      "Forgotten Crossroads",
      "Greenpath",
      "City of Tears",
      "Fungal Wastes",
      "Royal Waterways",
      "Deepnest",
      "Ancient Basin",
      "Kingdom's Edge",
      "Crystal Peak",
      "Howling Cliffs",
      "Queen's Gardens",
      "Fog Canyon",
    ],
  },
  {
    icon: "/achievements/Achievement_Peace.png",
    name: "DREAM_BROKEN_VESSEL",
    percent: "28.8",
    description: "Defeat the Lost Kin",
    howToGet: "Defeat the dream version of the Broken Vessel boss, the Lost Kin, accessible by striking its corpse with the Dream Nail.",
    prerequisites: ["Dream Nail", "Broken Vessel Defeated"],
    location: ["Ancient Basin"],
  },
  {
    icon: "/achievements/Achievement_Awakening.png",
    name: "AWAKENING",
    percent: "28.4",
    description: "Collect 1800 Essence and awaken the Dream Nail",
    howToGet: "Collect 1800 essence from the Dream Nail",
    prerequisites: [],
    location: [],
  },
  {
    icon: "/achievements/Achievement_Rivalry.png",
    name: "ZOTE",
    percent: "27.5",
    description: "Defeat Zote in the Colosseum of Fools.",
    howToGet: "Defeat Zote at the first trial of the Colosseum of Fools",
    prerequisites: [],
    location: ["Kingdom's Edge"],
  },
  {
    icon: "/achievements/Achievement_Strength.png",
    name: "DREAM_FK",
    percent: "25.0",
    description: "Defeat the Failed Champion.",
    howToGet: "Defeat the dream version of the False Knight boss, the Failed Champion, accessible by striking its corpse with the Dream Nail.",
    prerequisites: ["Dream Nail", "False Knight Defeated"],
    location: ["Forgotten Crossroads"],
  },
  {
    icon: "/achievements/Achievement_Grand_Performance.png",
    name: "GRIMM",
    percent: "24.9",
    description: "Defeat Grimm.",
    howToGet: "Defeat the Grimm boss found in the Grimm Troupe tent in Howling Cliffs after starting the Grimm Troupe questline.",
    prerequisites: [],
    location: ["Howling Cliffs"],
  },
  {
    icon: "/achievements/Achievement_Metamorphosis.png",
    name: "METAMORPHOSIS",
    percent: "24.8",
    description: "Rescue all of the imprisoned grubs",
    howToGet: "Find and acquire all 46 imprisoned grups",
    prerequisites: [],
    location: [],
  },
  {
    icon: "/achievements/Achievement_Void.png",
    name: "VOID",
    percent: "24.2",
    description: "Remember the past and unite the Abyss.",
    howToGet: "Find and acquire the Void Heart charm in the Abyss. You must first collect two pieces of the Kingsoul charm. The first is given by the White Lady in Queen's Garden. The second part requires beating the White Palace at Ancient Basin.",
    prerequisites: ["Mantis Claw"],
    location: ["Queen's Garden", "Ancient Basin"],
  },
  {
    icon: "/achievements/Achievement_Worldsoul.png",
    name: "WORLDSOUL",
    percent: "24.0",
    description: "Acquire all Vessel Fragments.",
    howToGet: "Find and collect all nine Vessel Fragments. These will increase your Souls slots by three.",
    prerequisites: [],
    location: [
      "Forgotten Crossroads",
      "Greenpath",
      "City of Tears",
      "Fungal Wastes",
      "Royal Waterways",
      "Deepnest",
      "Ancient Basin",
      "Kingdom's Edge",
      "Crystal Peak",
    ],
  },
  {
    icon: "/achievements/Achievement_Witness.png",
    name: "QUIRREL_EPILOGUE",
    percent: "23.4",
    description: "Spend a final moment with Quirrel.",
    howToGet: "After defeating the Watcher Knight and Lurien the Watcher, find Quirrel sitting at the edge of the Blue Lake in Fog Canyon.",
    prerequisites: ["Defeat Watcher Knight", "Defeat Lurien the Watcher"],
    location: ["Fog Canyon"],
  },
  {
    icon: "/achievements/Achievement_Mortality.png",
    name: "DREAM_SOUL_MASTER_DEFEAT",
    percent: "22.6",
    description: "Defeat the Soul Tyrant.",
    howToGet: "Defeat the dream version of the Soul Master boss, the Soul Tyrant, accessible by striking its corpse with the Dream Nail.",
    prerequisites: ["Dream Nail", "Soul Master Defeated"],
    location: ["City of Tears"],
  },
  {
    icon: "/achievements/Achievement_The_Hollow_Knight.png",
    name: "ENDING_A",
    percent: "22.1",
    description: "Defeat the Hollow Knight.",
    howToGet: "Defeat the final boss, the Hollow Knight, in the Temple of the Black Egg.",
    prerequisites: [],
    location: ["Temple of the Black Egg"],
  },
  {
    icon: "/achievements/Achievement_Dark_Romance.png",
    name: "GREY_PRINCE",
    percent: "20.5",
    description: "Defeat Grey Prince Zote.",
    howToGet: "Defeat Grey Prince Zote in Bretta's dream after rescuing Zote in Greenpath and the City of Tears.",
    prerequisites: ["Rescue Zote (twice)", "Dream Nail"],
    location: ["Dirtmouth (Bretta's House)"],
  },
  {
    icon: "/achievements/Achievement_Solace.png",
    name: "MOURNER",
    percent: "19.9",
    description: "Bring peace to the Grey Mourner.",
    howToGet: "Complete the Delicate Flower questline by delivering the flower to the Grey Mourner in Queen's Gardens without it taking any damage.",
    prerequisites: [],
    location: ["Queen's Gardens"],
  },
  {
    icon: "/achievements/Achievement_Blessed.png",
    name: "BLESSED",
    percent: "19.3",
    description: "Acquire all Charms and receive Salubra's blessing",
    howToGet: "Find and collect all 40 Charms scattered throughout Hallownest and receive Salubra's blessing.",
    prerequisites: [],
    location: [],
  },
  {
    icon: "/achievements/Achievement_Ascension.png",
    name: "ASCENSION",
    percent: "19.1",
    description: "Collect 2400 Essence and hear the Seer's final words",
    howToGet: "Collect 2400 Essence from the Dream Nail.",
    prerequisites: [],
    location: [],
  },
  {
    icon: "/achievements/Achievement_Masked.png",
    name: "MASKED",
    percent: "19.0",
    description: "Acquire all Mask Shards",
    howToGet: "Collect all eight full Masks.",
    prerequisites: ["PROTECTED"],
    location: [
      "Forgotten Crossroads",
      "Greenpath",
      "City of Tears",
      "Fungal Wastes",
      "Royal Waterways",
      "Deepnest",
      "Ancient Basin",
      "Kingdom's Edge",
    ],
  },
  {
    icon: "/achievements/Achievement_Fool.png",
    name: "COLOSSEUM_3",
    percent: "18.7",
    description: "Complete the Trial of the Fool.",
    howToGet: "Survive and complete the final and most difficult trial in the Colosseum of Fools.",
    prerequisites: ["COLOSSEUM_2"],
    location: ["Kingdom's Edge"],
  },
  {
    icon: "/achievements/Achievement_Dream_No_More.png",
    name: "ENDING_C",
    percent: "18.2",
    description: "Defeat the Radiance and consume the light",
    howToGet: "Defeat the Hollow Knight after acquiring the Void Heart and the Dream Nail. This unlocks the true ending.",
    prerequisites: ["ENDING_A", "Dream Nail", "Void Heart"],
    location: ["Temple of the Black Egg"],
  },
  {
    icon: "/achievements/Achievement_Purity.png",
    name: "NAILSMITH_KILL",
    percent: "17.7",
    description: "Slay the Nailsmith with the Pure Nail",
    howToGet: "After the Nailsmith fully upgrades your nail, choose to strike him down when prompted.",
    prerequisites: ["All Nail Upgrades"],
    location: ["City of Tears"],
  },
  {
    icon: "/achievements/Achievement_Completion.png",
    name: "COMPLETION",
    percent: "17.6",
    description: "Achieve 100% game completion and finish the game",
    howToGet: "Reach 100% completion by collecting all items, upgrades, and completing all essential tasks. Then finish the game.",
    prerequisites: [],
    location: ["Hallownest"],
  },
  {
    icon: "/achievements/Achievement_Memory.png",
    name: "WHITE_DEFENDER",
    percent: "17.4",
    description: "Defeat White Defender.",
    howToGet: "Defeat the dream version of the Dung Defender, the White Defender in the pantheon",
    prerequisites: ["Dream Nail", "Dung Defender Defeated", "Godseeker found in Royal Waterways"],
    location: ["Godhome (Royal Waterways)"],
  },
  {
    icon: "/achievements/Achievement_Sealed_Siblings.png",
    name: "ENDING_B",
    percent: "17.4",
    description: "Defeat the Hollow Knight with Hornet by your side.",
    howToGet: "Defeat the Hollow Knight after acquiring the Void Heart. Hornet will assist in the fight.",
    prerequisites: ["Void Heart"],
    location: ["Temple of the Black Egg"],
  },
  {
    icon: "/achievements/Achievement_Brotherhood.png",
    name: "PANTHEON1",
    percent: "15.9",
    description: "Complete the Pantheon of the Master.",
    howToGet: "Defeat all bosses in the first Pantheon in Godhome.",
    prerequisites: ["Dreamnail", "Godseeker found in Royal Waterways"],
    location: ["Godhome (Royal Waterways)"],
  },
  {
    icon: "/achievements/Achievement_Inspiration.png",
    name: "PANTHEON2",
    percent: "15.0",
    description: "Complete the Pantheon of the Artist.",
    howToGet: "Defeat all bosses in the second Pantheon in Godhome.",
    prerequisites: ["PANTHEON1"],
    location: ["Godhome (Royal Waterways)"],
  },
  {
    icon: "/achievements/Achievement_Ritual.png",
    name: "NIGHTMARE_GRIMM",
    percent: "14.9",
    description: "Defeat the Nightmare King and complete the Ritual.",
    howToGet: "Defeat the more challenging version of Grimm after reaching the full power of the child (Grimm's Charm)",
    prerequisites: ["GRIMM", "Brumm Encountered"],
    location: ["Grimm Troupe Tent (Howling Cliffs)"],
  },
  {
    icon: "/achievements/Achievement_Focus.png",
    name: "PANTHEON3",
    percent: "11.0",
    description: "Complete the Pantheon of the Sage.",
    howToGet: "Defeat all bosses in the third Pantheon in Godhome.",
    prerequisites: ["PANTHEON2"],
    location: ["Godhome (Royal Waterways)"],
  },
  {
    icon: "/achievements/Achievement_Happy_Couple.png",
    name: "NAILSMITH_SPARE",
    percent: "9.6",
    description: "Allow the Nailsmith to find a new calling.",
    howToGet: "After the Nailsmith fully upgrades your nail, choose to walk away and leave him be. After that you can encounter him on Nailmaster Sheo's hut in Greenpath",
    prerequisites: ["All Nail Upgrades"],
    location: ["City of Tears"],
  },
  {
    icon: "/achievements/Achievement_Soul_and_Shade.png",
    name: "PANTHEON4",
    percent: "8.7",
    description: "Complete the Pantheon of the Knight.",
    howToGet: "Defeat all bosses in the fourth Pantheon in Godhome.",
    prerequisites: ["PANTHEON3"],
    location: ["Godhome (Royal Waterways)"],
  },
  {
    icon: "/achievements/Achievement_Banishment.png",
    name: "BANISHMENT",
    percent: "7.6",
    description: "Banish the Grimm Troupe.",
    howToGet: "Choose to banish the Grimm Troupe by speaking to Brumm in the Distant Village in Deepnest after lighting three Nightmare Lanterns.",
    prerequisites: ["Grimm Troupe Encountered", "Three Nightmare Lanterns Lit"],
    location: ["Deepnest (Distant Village)"],
  },
  {
    icon: "/achievements/Achievement_Keen_Hunter.png",
    name: "HUNTER_1",
    percent: "7.2",
    description: "Record all of Hallownest's creatures in the Hunter's Journal.",
    howToGet: "Fill out the Hunter's Journal by encountering and defeating every type of enemy at least once.",
    prerequisites: ["Hunter's Journal acquired from the Hunter in Greenpath"],
    location: ["Hallownest"],
  },
  {
    icon: "/achievements/Achievement_Neglect.png",
    name: "NEGLECT",
    percent: "7.2",
    description: "Leave Zote to die.",
    howToGet: "Fail to rescue Zote from one of the both enemy encounters by leaving him to be defeated.",
    prerequisites: ["Rescue Zote (twice)"],
    location: ["Greenpath", "City of Tears"],
  },
  {
    icon: "/achievements/Achievement_True_Hunter.png",
    name: "HUNTER_2",
    percent: "6.6",
    description: "Receive the Hunter's Mark.",
    howToGet: "After completing the Hunter's Journal, speak to the Hunter in Greenpath to receive all his notes.",
    prerequisites: ["HUNTER_1"],
    location: ["Greenpath"],
  },
  {
    icon: "/achievements/Achievement_Passing_of_the_Age.png",
    name: "MR_MUSHROOM",
    percent: "6.4",
    description: "Aid the Herald in moving on. ",
    howToGet: "Find Mr. Mushroom in all his seven locations across Hallownest after acquiring the Spore Shroom charm. At the final location in Fog Canyon, wait for his dialogue to complete.",
    prerequisites: ["Spore Shroom"],
    location: [
      "Fungal Wastes",
      "Deepnest",
      "Queen's Gardens",
      "Ancient Basin",
      "Howling Cliffs",
      "Kingdom's Edge",
      "Fog Canyon",
    ],
  },
  {
    icon: "/achievements/Achievement_Pure_Completion.png",
    name: "COMPLETIONGG",
    percent: "6.1",
    description: "Achieve 112% game completion.",
    howToGet: "Reach 112% completion by collecting all items, upgrades, defeating all bosses (including dream and DLC bosses), and completing all Pantheons up to Pantheon 5.",
    prerequisites: [],
    location: ["Hallownest"],
  },
  {
    icon: "/achievements/Achievement_Speedrun_1.png",
    name: "SPEEDRUN_1",
    percent: "5.9",
    description: "Complete the game in under 10 hours.",
    howToGet: "Finish the main storyline and defeat the Hollow Knight in under ten hours.",
    prerequisites: [],
    location: ["Temple of the Black Egg"],
  },
  {
    icon: "/achievements/Achievement_Speed_Completion.png",
    name: "SPEED_COMPLETION",
    percent: "5.0",
    description: "Achieve 100% game completion and finish the game in under 20 hours.",
    howToGet: "Reach 100% completion within twenty hours of playtime.",
    prerequisites: ["COMPLETION"],
    location: ["Hallownest"],
  },
  {
    icon: "/achievements/Achievement_Speedrun_2.png",
    name: "SPEEDRUN_2",
    percent: "4.9",
    description: "Complete the game in under 5 hours.",
    howToGet: "Finish the main storyline and defeat the Hollow Knight in under five hours.",
    prerequisites: [],
    location: ["Temple of the Black Egg"],
  },
  {
    icon: "/achievements/Achievement_Embrace_the_Void.png",
    name: "ENDINGD",
    percent: "4.7",
    description: "Ascend the Pantheon of Hallownest and take your place at its peak.",
    howToGet: "Complete the Pantheon of Hallownest (Pantheon 5) in Godhome.",
    prerequisites: ["PANTHEON4"],
    location: ["Godhome (Royal Waterways)"],
  },
  {
    icon: "/achievements/Achievement_Steel_Soul.png",
    name: "STEELSOUL",
    percent: "4.2",
    description: "Finish the game in Steel Soul mode.",
    howToGet: "Finish the game in Steel Soul Mode, where death means the end of the run.",
    prerequisites: ["Game Completion"],
    location: ["Temple of the Black Egg"],
  },
  {
    icon: "/achievements/Achievement_Steel_Heart.png",
    name: "STEELSOUL_COMPLETION",
    percent: "3.5",
    description: "Achieve 100% game completion and finish the game in Steel Soul mode.",
    howToGet: "Reach 100% completion in Steel Soul Mode.",
    prerequisites: ["STEELSOUL", "COMPLETION"],
    location: ["Hallownest"],
  },
]

export enum AchievementName {
  CHARMED = "Charmed",
  FK_DEFEAT = "Falsehood",
  HORNET_1 = "Test of Resolve",
  STAG_STATION_HALF = "Connection",
  PROTECTED = "Protected",
  SOUL_MASTER_DEFEAT = "Illumination",
  MANTIS_LORDS = "Respect",
  SOULFUL = "Soulful",
  DUNG_DEFENDER = "Honour",
  BROKEN_VESSEL = "Release",
  ENCHANTED = "Enchanted",
  BEAST = "Beast",
  GRUBFRIEND = "Grubfriend",
  HORNET_2 = "Proof of Resolve",
  ATTUNEMENT = "Attunement",
  COLOSSEUM_1 = "Warrior",
  TEACHER = "Teacher",
  WATCHER = "Watcher",
  MAP = "Cartographer",
  COLOSSEUM_2 = "Conqueror",
  STAG_STATION_ALL = "Hope",
  TRAITOR_LORD = "Execution",
  COLLECTOR = "Obsession",
  DREAM_BROKEN_VESSEL = "Peace",
  AWAKENING = "Awakening",
  ZOTE = "Rivalry",
  DREAM_FK = "Strengh",
  GRIMM = "Grand Performance",
  METAMORPHOSIS = "Metamorphosis",
  VOID = "Void",
  WORLDSOUL = "Worldsoul",
  QUIRREL_EPILOGUE = "Witness",
  DREAM_SOUL_MASTER_DEFEAT = "Mortality",
  ENDING_A = "The Hollow Knight",
  GREY_PRINCE = "Dark Romance",
  MOURNER = "Solace",
  BLESSED = "Blessed",
  ASCENSION = "Ascension",
  MASKED = "Masked",
  COLOSSEUM_3 = "Fool",
  ENDING_C = "Dream No More",
  NAILSMITH_KILL = "Purity",
  COMPLETION = "Completion",
  WHITE_DEFENDER = "Memory",
  ENDING_B = "Sealed Siblings",
  PANTHEON1 = "Brotherhood",
  PANTHEON2 = "Inspiration",
  NIGHTMARE_GRIMM = "Ritual",
  PANTHEON3 = "Focus",
  NAILSMITH_SPARE = "Happy Couple",
  PANTHEON4 = "Soul & Shade",
  BANISHMENT = "Banishment",
  HUNTER_1 = "Keen Hunter",
  NEGLECT = "Neglect",
  HUNTER_2 = "True Hunter",
  MR_MUSHROOM = "Passing of the Age",
  COMPLETIONGG = "Pure Completion",
  SPEEDRUN_1 = "Speedrun 1",
  SPEED_COMPLETION = "Speed Completion",
  SPEEDRUN_2 = "Speedrun 2",
  ENDINGD = "Embrace the Void",
  STEELSOUL = "Steelsoul",
  STEELSOUL_COMPLETION = "Steel Heart",
}

export const mapApiAchievementsToEnum = (
  apiAchievements: {
    icon: string;
    name: string;
    percent: string;
    description: string;
    howToGet: string;
    prerequisites: string[];
    location: string[];
  }[]
): {
  icon: string;
  name: AchievementName;
  percent: string;
  description: string;
  howToGet: string;
  prerequisites: string[];
  location: string[];
}[] => {
  return apiAchievements.map((apiAchievement) => {
    const enumKey = apiAchievement.name.toUpperCase().replace(/ /g, "_");
    if (AchievementName[enumKey as keyof typeof AchievementName]) {
      return {
        icon: apiAchievement.icon,
        name: AchievementName[enumKey as keyof typeof AchievementName],
        percent: apiAchievement.percent,
        description: apiAchievement.description,
        howToGet: apiAchievement.howToGet,
        prerequisites: apiAchievement.prerequisites,
        location: apiAchievement.location,
      };
    } else {
      console.warn(`Conquista não encontrada no enum: ${apiAchievement.name}`);
      return {
        icon: apiAchievement.icon,
        name: apiAchievement.name as AchievementName,
        percent: apiAchievement.percent,
        description: apiAchievement.description,
        howToGet: apiAchievement.howToGet,
        prerequisites: apiAchievement.prerequisites,
        location: apiAchievement.location,
      };
    }
  });
};

export const processedAchievements = mapApiAchievementsToEnum(achievementsAPI);
console.log(processedAchievements);
